"""
app/backend/genie_agent.py
===========================
Databricks Genie AI/BI client using the official Databricks SDK.

Usage pattern (matching confirmed working SDK API):

    w.genie.start_conversation_and_wait(space_id, content)
        → GenieMessage  (new conversation)

    w.genie.create_message_and_wait(space_id, conversation_id, content)
        → GenieMessage  (follow-up in same conversation)

Each GenieMessage has:
    .conversation_id  str
    .message_id       str
    .attachments      list[GenieAttachment]
        attachment.text    → GenieAttachmentText  (.content)
        attachment.query   → GenieAttachmentQuery (.query, .description)

SQL from .query.query is executed via databricks-sql-connector so the
Streamlit app gets back a pandas DataFrame alongside the narrative text.
"""

import sys
import pandas as pd
from pathlib import Path
from typing import Optional

sys.path.insert(0, str(Path(__file__).parent.parent.parent))
from config import (
    DATABRICKS_HOST, DATABRICKS_TOKEN, DATABRICKS_HTTP_PATH,
    GENIE_SPACE_ID,
)


# ---------------------------------------------------------------------------
# SDK client factory
# ---------------------------------------------------------------------------

def _workspace_client():
    """
    Return an authenticated WorkspaceClient.

    Inside a Databricks notebook WorkspaceClient() picks up credentials
    automatically.  Outside (e.g. running Streamlit locally) it uses the
    host + token from .env.
    """
    from databricks.sdk import WorkspaceClient

    if DATABRICKS_HOST and DATABRICKS_TOKEN:
        return WorkspaceClient(
            host=DATABRICKS_HOST,
            token=DATABRICKS_TOKEN,
        )
    # Auto-auth (Databricks notebook / cluster environment)
    return WorkspaceClient()


# ---------------------------------------------------------------------------
# SQL execution via Databricks SQL connector
# ---------------------------------------------------------------------------

def _run_sql(sql: str) -> pd.DataFrame:
    """Execute SQL on the configured SQL warehouse, return a pandas DataFrame."""
    from databricks import sql as dbsql

    with dbsql.connect(
        server_hostname=DATABRICKS_HOST.replace("https://", ""),
        http_path=DATABRICKS_HTTP_PATH,
        access_token=DATABRICKS_TOKEN,
    ) as conn:
        with conn.cursor() as cursor:
            cursor.execute(sql)
            return cursor.fetchall_arrow().to_pandas()


# ---------------------------------------------------------------------------
# Attachment parsing
# ---------------------------------------------------------------------------

def _parse_attachments(message) -> tuple[Optional[str], Optional[str]]:
    """
    Extract (sql, description) from a GenieMessage's attachments.

    Priority:
      - sql         → first attachment that has a .query field
      - description → .query.description if present, else first .text.content
    """
    sql         = None
    description = None

    for att in (message.attachments or []):
        if att.query:
            if sql is None:
                sql = att.query.query
            if description is None and att.query.description:
                description = att.query.description
        if att.text and description is None:
            description = att.text.content

    return sql, description


# ---------------------------------------------------------------------------
# Public interface
# ---------------------------------------------------------------------------

def ask_genie(
    question: str,
    conversation_id: Optional[str] = None,
) -> dict:
    """
    Send a natural-language question to the configured Databricks Genie space.

    Args:
        question        : Plain-English question from the buyer.
        conversation_id : ID from a previous call to continue the same
                          conversation (Genie retains full context).
                          Pass None to start a fresh conversation.

    Returns a dict:
        sql             : SQL string generated by Genie  (str | None)
        results         : Query results as pandas DataFrame  (None on error)
        description     : Genie's plain-English narrative  (str | None)
        conversation_id : Pass back on the next call for follow-up questions
        message_id      : ID of this specific message
        error           : Error string if the call failed, else None
    """
    # ── Guard: required config ─────────────────────────────────────────────
    if not GENIE_SPACE_ID:
        return _error(
            conversation_id,
            "GENIE_SPACE_ID is not set. "
            "Run notebook 05_setup_genie_space in Databricks, create the Genie "
            "space, then add GENIE_SPACE_ID=<id> to your .env file.",
        )

    try:
        w = _workspace_client()

        # ── Call Genie (SDK handles polling automatically) ─────────────────
        if conversation_id:
            # Follow-up question in the same conversation
            message = w.genie.create_message_and_wait(
                space_id=GENIE_SPACE_ID,
                conversation_id=conversation_id,
                content=question,
            )
        else:
            # New conversation
            message = w.genie.start_conversation_and_wait(
                space_id=GENIE_SPACE_ID,
                content=question,
            )

        # ── Extract SQL + description from attachments ─────────────────────
        sql, description = _parse_attachments(message)

        # ── Execute the SQL to get a DataFrame ────────────────────────────
        results = None
        if sql and DATABRICKS_HTTP_PATH:
            try:
                results = _run_sql(sql)
            except Exception as sql_err:
                description = (description or "") + f"\n\n⚠️ SQL execution error: {sql_err}"

        return {
            "sql":             sql,
            "results":         results,
            "description":     description,
            "conversation_id": message.conversation_id,
            "message_id":      message.message_id,
            "error":           None,
        }

    except Exception as e:
        return _error(conversation_id, str(e))


# ---------------------------------------------------------------------------
# Internal helper
# ---------------------------------------------------------------------------

def _error(conversation_id: Optional[str], msg: str) -> dict:
    return {
        "sql":             None,
        "results":         None,
        "description":     None,
        "conversation_id": conversation_id,
        "message_id":      None,
        "error":           msg,
    }
