"""
app/backend/genie_agent.py
===========================
Databricks Genie AI/BI REST API client.

Flow per question:
  1. POST  /spaces/{space_id}/start-conversation      → conversation_id, message_id
  2. GET   /spaces/{space_id}/conversations/{c}/messages/{m}   (poll status)
  3. GET   /spaces/{space_id}/conversations/{c}/messages/{m}/query-result
  4. Execute the SQL via Databricks SQL connector to return a pandas DataFrame

Follow-up questions within the same session reuse the conversation_id so
Genie has full context of the prior exchange.
"""

import sys
import time
import requests
import pandas as pd
from pathlib import Path
from typing import Optional

sys.path.insert(0, str(Path(__file__).parent.parent.parent))
from config import (
    DATABRICKS_HOST, DATABRICKS_TOKEN, DATABRICKS_HTTP_PATH,
    GENIE_SPACE_ID, CATALOG, SCHEMA,
)

_BASE_URL = f"{DATABRICKS_HOST.rstrip('/')}/api/2.0/genie"
_POLL_INTERVAL = 2   # seconds between status checks
_POLL_TIMEOUT  = 90  # seconds before giving up


# ---------------------------------------------------------------------------
# Internal HTTP helpers
# ---------------------------------------------------------------------------

def _headers() -> dict:
    return {
        "Authorization": f"Bearer {DATABRICKS_TOKEN}",
        "Content-Type":  "application/json",
    }


def _post(path: str, body: dict) -> dict:
    url  = f"{_BASE_URL}/{path}"
    resp = requests.post(url, headers=_headers(), json=body, timeout=30)
    resp.raise_for_status()
    return resp.json()


def _get(path: str) -> dict:
    url  = f"{_BASE_URL}/{path}"
    resp = requests.get(url, headers=_headers(), timeout=30)
    resp.raise_for_status()
    return resp.json()


# ---------------------------------------------------------------------------
# Genie conversation helpers
# ---------------------------------------------------------------------------

def _start_conversation(question: str) -> tuple[str, str]:
    """Start a new Genie conversation. Returns (conversation_id, message_id)."""
    data = _post(
        f"spaces/{GENIE_SPACE_ID}/start-conversation",
        {"content": question},
    )
    return data["conversation_id"], data["message_id"]


def _create_message(conversation_id: str, question: str) -> str:
    """Send a follow-up message. Returns message_id."""
    data = _post(
        f"spaces/{GENIE_SPACE_ID}/conversations/{conversation_id}/messages",
        {"content": question},
    )
    return data["message_id"]


def _poll_message(conversation_id: str, message_id: str) -> dict:
    """Poll until the message reaches a terminal status."""
    path      = f"spaces/{GENIE_SPACE_ID}/conversations/{conversation_id}/messages/{message_id}"
    deadline  = time.time() + _POLL_TIMEOUT
    terminal  = {"COMPLETED", "FAILED", "CANCELLED", "QUERY_RESULT_EXPIRED"}

    while time.time() < deadline:
        msg = _get(path)
        if msg.get("status") in terminal:
            return msg
        time.sleep(_POLL_INTERVAL)

    raise TimeoutError(f"Genie did not respond within {_POLL_TIMEOUT}s")


def _extract_attachments(msg: dict) -> tuple[Optional[str], Optional[str]]:
    """
    Pull SQL query and plain-text description from Genie message attachments.
    Returns (sql, description).
    """
    sql         = None
    description = None

    for att in msg.get("attachments", []):
        if att.get("query"):
            sql         = att["query"].get("query")
            description = att["query"].get("description") or description
        if att.get("text"):
            description = att["text"].get("content") or description

    return sql, description


# ---------------------------------------------------------------------------
# SQL execution via Databricks SQL connector
# ---------------------------------------------------------------------------

def _run_sql(sql: str) -> pd.DataFrame:
    """Execute SQL on a Databricks SQL warehouse and return a pandas DataFrame."""
    from databricks import sql as dbsql

    with dbsql.connect(
        server_hostname=DATABRICKS_HOST.replace("https://", ""),
        http_path=DATABRICKS_HTTP_PATH,
        access_token=DATABRICKS_TOKEN,
    ) as conn:
        with conn.cursor() as cursor:
            cursor.execute(sql)
            return cursor.fetchall_arrow().to_pandas()


# ---------------------------------------------------------------------------
# Public interface
# ---------------------------------------------------------------------------

def ask_genie(
    question: str,
    conversation_id: Optional[str] = None,
) -> dict:
    """
    Send a natural-language question to the Databricks Genie space.

    Args:
        question        : The buyer's question in plain English.
        conversation_id : Pass the id from a previous call to continue the
                          same conversation (Genie retains context).

    Returns a dict with:
        sql             : SQL generated by Genie (str | None)
        results         : Query results as a pandas DataFrame (None on error)
        description     : Genie's plain-English narrative answer (str | None)
        conversation_id : Use this in the next call for follow-up questions
        message_id      : ID of this specific message
        error           : Error string if the call failed, else None
    """
    if not GENIE_SPACE_ID:
        return {
            "sql": None, "results": None, "description": None,
            "conversation_id": None, "message_id": None,
            "error": (
                "GENIE_SPACE_ID is not configured. "
                "Run notebook 05_setup_genie_space and add the ID to your .env file."
            ),
        }

    if not DATABRICKS_HOST or not DATABRICKS_TOKEN:
        return {
            "sql": None, "results": None, "description": None,
            "conversation_id": None, "message_id": None,
            "error": "DATABRICKS_HOST and DATABRICKS_TOKEN must be set in .env",
        }

    try:
        # ── 1. Start or continue conversation ─────────────────────────────────
        if conversation_id:
            message_id = _create_message(conversation_id, question)
        else:
            conversation_id, message_id = _start_conversation(question)

        # ── 2. Poll for completion ─────────────────────────────────────────────
        msg = _poll_message(conversation_id, message_id)

        if msg.get("status") != "COMPLETED":
            return {
                "sql": None, "results": None, "description": None,
                "conversation_id": conversation_id, "message_id": message_id,
                "error": f"Genie returned status: {msg.get('status')}",
            }

        # ── 3. Extract SQL and description from attachments ────────────────────
        sql, description = _extract_attachments(msg)

        # ── 4. Execute SQL to get results ──────────────────────────────────────
        results = None
        if sql and DATABRICKS_HTTP_PATH:
            try:
                results = _run_sql(sql)
            except Exception as sql_err:
                description = (description or "") + f"\n\n⚠️ Could not execute SQL: {sql_err}"

        return {
            "sql":             sql,
            "results":         results,
            "description":     description,
            "conversation_id": conversation_id,
            "message_id":      message_id,
            "error":           None,
        }

    except TimeoutError as e:
        return {
            "sql": None, "results": None, "description": None,
            "conversation_id": conversation_id, "message_id": None,
            "error": str(e),
        }
    except requests.HTTPError as e:
        return {
            "sql": None, "results": None, "description": None,
            "conversation_id": conversation_id, "message_id": None,
            "error": f"Genie API error {e.response.status_code}: {e.response.text[:300]}",
        }
    except Exception as e:
        return {
            "sql": None, "results": None, "description": None,
            "conversation_id": None, "message_id": None,
            "error": str(e),
        }
